// Font Tester Text Constants

export const FONT_TESTER_TEXTS = [
  "Insert Coin Here",
  "Brother, Amen (Sample)",
  "Executive Order 6102",
  "Tape packs and flyers",
  "Ah, certainly",
  "Die looted",
  "On any goods",
  "Statutory time limit",
  "International Klein blue",
  "Manufactured to destroy rigs",
  "Please do not bend",
  "Renegade Hardware",
  "Moving Shadow",
  "The End",
  "Plastic People",
  "One Nation",
  "Error Loading",
  "White socks",
  "Dial-up",
  "QuarkXpress and Freehand",
  "Personal software",
  "94.5/94.6 FM",
  "100.3/100.4 FM",
  "Under the arches",
  "Boogie Times",
  "Music Power",
  "Skeng",
  "3 minute apps",
  "No product exits",
];
